// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type PageDocumentDataSlicesSlice =
  | KeyTopicsSlice
  | DeepDiveSlice
  | FoldableSlice
  | HeroSlice
  | WordcloudSlice
  | ImageTextSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Content for Person documents
 */
interface PersonDocumentData {
  /**
   * Title field in *Person*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: person.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Text field in *Person*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: person.text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;
}

/**
 * Person document from Prismic
 *
 * - **API ID**: `person`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PersonDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PersonDocumentData>, "person", Lang>;

export type AllDocumentTypes = PageDocument | PersonDocument;

/**
 * Item in *DeepDives → Default → Primary → DeepDive*
 */
export interface DeepDiveSliceDefaultPrimaryDeepdiveItem {
  /**
   * Title field in *DeepDives → Default → Primary → DeepDive*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: deep_dive.default.primary.deepdive[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Date field in *DeepDives → Default → Primary → DeepDive*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: deep_dive.default.primary.deepdive[].date
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  date: prismic.KeyTextField;

  /**
   * Text field in *DeepDives → Default → Primary → DeepDive*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: deep_dive.default.primary.deepdive[].text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * Image field in *DeepDives → Default → Primary → DeepDive*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: deep_dive.default.primary.deepdive[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Key Takeaways field in *DeepDives → Default → Primary → DeepDive*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: deep_dive.default.primary.deepdive[].key_takeaways
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  key_takeaways: prismic.RichTextField;

  /**
   * Connected Person  field in *DeepDives → Default → Primary → DeepDive*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: deep_dive.default.primary.deepdive[].connected_person
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  connected_person: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Primary content in *DeepDives → Default → Primary*
 */
export interface DeepDiveSliceDefaultPrimary {
  /**
   * DeepDive field in *DeepDives → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: deep_dive.default.primary.deepdive[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  deepdive: prismic.GroupField<
    Simplify<DeepDiveSliceDefaultPrimaryDeepdiveItem>
  >;
}

/**
 * Default variation for DeepDives Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DeepDiveSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DeepDiveSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *DeepDives*
 */
type DeepDiveSliceVariation = DeepDiveSliceDefault;

/**
 * DeepDives Shared Slice
 *
 * - **API ID**: `deep_dive`
 * - **Description**: DeepDive
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DeepDiveSlice = prismic.SharedSlice<
  "deep_dive",
  DeepDiveSliceVariation
>;

/**
 * Item in *Foldable → Default → Primary → Foldable*
 */
export interface FoldableSliceDefaultPrimaryFoldableItem {
  /**
   * Title field in *Foldable → Default → Primary → Foldable*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: foldable.default.primary.foldable[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Text field in *Foldable → Default → Primary → Foldable*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: foldable.default.primary.foldable[].text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;
}

/**
 * Primary content in *Foldable → Default → Primary*
 */
export interface FoldableSliceDefaultPrimary {
  /**
   * Title field in *Foldable → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: foldable.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Text field in *Foldable → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: foldable.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * Foldable field in *Foldable → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: foldable.default.primary.foldable[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  foldable: prismic.GroupField<
    Simplify<FoldableSliceDefaultPrimaryFoldableItem>
  >;

  /**
   * Credits field in *Foldable → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: foldable.default.primary.credits
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  credits: prismic.RichTextField;
}

/**
 * Default variation for Foldable Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FoldableSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FoldableSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Foldable*
 */
type FoldableSliceVariation = FoldableSliceDefault;

/**
 * Foldable Shared Slice
 *
 * - **API ID**: `foldable`
 * - **Description**: Foldable
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FoldableSlice = prismic.SharedSlice<
  "foldable",
  FoldableSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Text field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * Button field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *ImageText → Default → Primary*
 */
export interface ImageTextSliceDefaultPrimary {
  /**
   * Title field in *ImageText → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Text field in *ImageText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * Image field in *ImageText → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for ImageText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ImageText*
 */
type ImageTextSliceVariation = ImageTextSliceDefault;

/**
 * ImageText Shared Slice
 *
 * - **API ID**: `image_text`
 * - **Description**: ImageText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageTextSlice = prismic.SharedSlice<
  "image_text",
  ImageTextSliceVariation
>;

/**
 * Item in *KeyTopics → Default → Primary → Topics*
 */
export interface KeyTopicsSliceDefaultPrimaryTopicsItem {
  /**
   * Title field in *KeyTopics → Default → Primary → Topics*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: key_topics.default.primary.topics[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Text field in *KeyTopics → Default → Primary → Topics*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: key_topics.default.primary.topics[].text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;
}

/**
 * Primary content in *KeyTopics → Default → Primary*
 */
export interface KeyTopicsSliceDefaultPrimary {
  /**
   * Title field in *KeyTopics → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: key_topics.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Text field in *KeyTopics → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: key_topics.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * Topics field in *KeyTopics → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: key_topics.default.primary.topics[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  topics: prismic.GroupField<Simplify<KeyTopicsSliceDefaultPrimaryTopicsItem>>;
}

/**
 * Default variation for KeyTopics Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type KeyTopicsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<KeyTopicsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *KeyTopics*
 */
type KeyTopicsSliceVariation = KeyTopicsSliceDefault;

/**
 * KeyTopics Shared Slice
 *
 * - **API ID**: `key_topics`
 * - **Description**: KeyTopics
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type KeyTopicsSlice = prismic.SharedSlice<
  "key_topics",
  KeyTopicsSliceVariation
>;

/**
 * Item in *Wordcloud → Default → Primary → Words*
 */
export interface WordcloudSliceDefaultPrimaryWordsItem {
  /**
   * Word field in *Wordcloud → Default → Primary → Words*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: wordcloud.default.primary.words[].word
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  word: prismic.KeyTextField;
}

/**
 * Primary content in *Wordcloud → Default → Primary*
 */
export interface WordcloudSliceDefaultPrimary {
  /**
   * Title field in *Wordcloud → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: wordcloud.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Text field in *Wordcloud → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: wordcloud.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * Words field in *Wordcloud → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: wordcloud.default.primary.words[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  words: prismic.GroupField<Simplify<WordcloudSliceDefaultPrimaryWordsItem>>;
}

/**
 * Default variation for Wordcloud Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type WordcloudSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WordcloudSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Wordcloud*
 */
type WordcloudSliceVariation = WordcloudSliceDefault;

/**
 * Wordcloud Shared Slice
 *
 * - **API ID**: `wordcloud`
 * - **Description**: Wordcloud
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type WordcloudSlice = prismic.SharedSlice<
  "wordcloud",
  WordcloudSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      PersonDocument,
      PersonDocumentData,
      AllDocumentTypes,
      DeepDiveSlice,
      DeepDiveSliceDefaultPrimaryDeepdiveItem,
      DeepDiveSliceDefaultPrimary,
      DeepDiveSliceVariation,
      DeepDiveSliceDefault,
      FoldableSlice,
      FoldableSliceDefaultPrimaryFoldableItem,
      FoldableSliceDefaultPrimary,
      FoldableSliceVariation,
      FoldableSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      ImageTextSlice,
      ImageTextSliceDefaultPrimary,
      ImageTextSliceVariation,
      ImageTextSliceDefault,
      KeyTopicsSlice,
      KeyTopicsSliceDefaultPrimaryTopicsItem,
      KeyTopicsSliceDefaultPrimary,
      KeyTopicsSliceVariation,
      KeyTopicsSliceDefault,
      WordcloudSlice,
      WordcloudSliceDefaultPrimaryWordsItem,
      WordcloudSliceDefaultPrimary,
      WordcloudSliceVariation,
      WordcloudSliceDefault,
    };
  }
}
