// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  deep_dive: dynamic(() => import("./Carousel")),
  deepdives: dynamic(() => import("./Deepdives")),
  foldable: dynamic(() => import("./Foldable")),
  footer: dynamic(() => import("./Footer")),
  hero: dynamic(() => import("./Hero")),
  image_text: dynamic(() => import("./ImageText")),
  key_topics: dynamic(() => import("./KeyTopics")),
  wordcloud: dynamic(() => import("./Wordcloud")),
};
