// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  foldable: dynamic(() => import("./Foldable")),
  hero: dynamic(() => import("./Hero")),
  image_text: dynamic(() => import("./ImageText")),
  wordcloud: dynamic(() => import("./Wordcloud")),
};
